# ================================ NOTE =================================
# All possible keys:
# - Letters.        a, b, c, ..., z
# - Numbers.        0, 1, 2, ..., 9
# - Keypad numbers. keypad0, keypad1, keypad2, ..., keypad9
# - F-keys.         f1, f2, ..., f20
# - Special keys.   minus, equal, period, comma, slash, backslash, quote, semicolon, backtick,
#                   leftSquareBracket, rightSquareBracket, space, enter, esc, backspace, tab
# - Keypad special. keypadClear, keypadDecimalMark, keypadDivide, keypadEnter, keypadEqual,
#                   keypadMinus, keypadMultiply, keypadPlus
# - Arrows.         left, down, up, right

# All possible modifiers: cmd, alt, ctrl, shift
# All possible commands: https://nikitabobko.github.io/AeroSpace/commands
# ========================================================================

# start options
after-login-command = []
after-startup-command = []
start-at-login = true

# Normalizations
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Possible values: tiles|accordion
default-root-container-layout = 'accordion'

# Possible values: horizontal|vertical|auto
# 'auto' means: wide monitor (anything wider than high) gets horizontal orientation,
#               tall monitor (anything higher than wide) gets vertical orientation
default-root-container-orientation = 'auto'

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']

# move mouse to the center of the window when focus changes
on-focus-changed = ['move-mouse window-lazy-center']

# turn off cmd-h and cmd-alt-h
automatically-unhide-macos-hidden-apps = true

# accordion-padding
accordion-padding = 10

# keyboard layout
[key-mapping]
preset = 'qwerty'

# Gaps between windows
[gaps]
inner.vertical = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]
outer.left = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]
inner.horizontal = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]
outer.bottom = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]
outer.top = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]
outer.right = [
    { monitor."Built-in Retina Display" = 16 },
    { monitor."DELL P2723QE" = 16 },
    16,
]

# 'main' binding mode declaration
[mode.main.binding]

# disable cmd-h and cmd-alt-h
cmd-h = []
cmd-alt-h = []

# Change layout (binded to karabiner-window_hyper)
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Focus window (binded to karabiner-window_hyper)
alt-j = 'focus left'
alt-k = 'focus down'
alt-i = 'focus up'
alt-l = 'focus right'

alt-shift-ctrl-j = ['join-with left', 'mode main']
alt-shift-ctrl-k = ['join-with down', 'mode main']
alt-shift-ctrl-i = ['join-with up', 'mode main']
alt-shift-ctrl-l = ['join-with right', 'mode main']

# Move window (binded to karabiner-window_hyper)
alt-shift-j = 'move left'
alt-shift-k = 'move down'
alt-shift-i = 'move up'
alt-shift-l = 'move right'

# Resize window (binded to karabiner-window_hyper)
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Move to workspace (binded to karabiner-window_hyper)
alt-1 = 'workspace 1' # code / personal
alt-2 = 'workspace 2' # browser
alt-3 = 'workspace 3' # agenda
alt-4 = 'workspace 4' # finder / preview
alt-5 = 'workspace 5' # communication
alt-6 = 'workspace 6' # play
alt-shift-h = 'workspace-back-and-forth'
# alt-7 = 'workspace 7' # mac retina display
# alt-8 = 'workspace 8' # mac retina display

# Fullscreen (binded to karabiner-window_hyper)
alt-shift-f = 'fullscreen'

# Switch to service mode (binded to karabiner-window_hyper)
alt-shift-semicolon = 'mode service'

# Move window to workspace (binded to karabiner-window_hyper_sublayer_m)
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-6 = ['move-node-to-workspace 6', 'workspace 6']
# alt-shift-7 = ['move-node-to-workspace 7', 'workspace 7']
# alt-shift-8 = ['move-node-to-workspace 8', 'workspace 8']

# move window back to original workspace

# Service mode 
[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
f = [
    'layout floating tiling',
    'mode main',
] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']


# On window detected 

# Move to workspace
[[on-window-detected]]
if.app-id = 'com.microsoft.VSCode' # vscode
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.exafunction.windsurf' # windsurf
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.jetbrains.datagrip' # datagrip
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'com.jetbrains.intellij' # intellij
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'dev.warp.Warp-Stable' # WARP
run = ['move-node-to-workspace 1']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen' # zen browser
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'company.thebrowser.Browser' # Arc Browser
check-further-callbacks = true
run = ['move-node-to-workspace 2']

[[on-window-detected]]
if.app-id = 'com.apple.iCal'       # calendar
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.reminders'  # reminders
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'notion.id'            # notion
run = ['move-node-to-workspace 3']

[[on-window-detected]]
if.app-id = 'com.apple.finder' # finder
run = ['move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.iWork.Keynote' # keynote
run = ['layout floating', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.apple.Preview' # preview
run = ['layout floating', 'move-node-to-workspace 4']

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap' # slack
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.readdle.SparkDesktop-setapp' # spark mail
run = ['move-node-to-workspace 5']

[[on-window-detected]]
if.app-id = 'com.spotify.client'   # spotify
run = ['move-node-to-workspace 6']

# Floating windows
[[on-window-detected]]
if.app-id = 'com.riotgames.LeagueofLegends.LeagueClientUx'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.riotgames.RiotGames.RiotClient' # League of Legends launcher
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.getcleanshot.app-setapp' # CleanShot X
check-further-callbacks = true
run = ['layout floating']

[[on-window-detected]]
if.app-id = 'app.zen-browser.zen' # Zen Browser pip
if.window-title-regex-substring = 'Picture-in-Picture'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'com.kakao.KakaoTalkMac'
run = 'layout floating'

[[on-window-detected]]
if.app-id = 'org.pqrs.Karabiner-Elements.Settings'
run = 'layout floating'

# Workspace to monitor force assignment
[workspace-to-monitor-force-assignment]
1 = 'main'
2 = 'main'
3 = 'main'
4 = 'main'
5 = 'main'
6 = 'Built-in Retina Display'
